### ISSUE TITLE
Extremely long GFA generation time for complex assemblies

### ISSUE THREAD

**Issue by bresyd** [fenderglass/ABruijn#234]
Dear Mikhail,

thanks for providing us with a the latest flye2.7 release. I am particularly interested in it since you mention that there are improvements for the assembly of complex metagenomes, which is what I am trying to do.

I used the 2.7 version (installed via 'conda install flye') to assemble an environmental metagenome, using pacbio ccs reads (24Gb large fastq file). While the assembly did finish successfully, it did take multiple days for it to get there, which is much longer compared to previous assemblies I did. 
Hence, I reinstalled the last 2.6-release (wget https://github.com/fenderglass/Flye/archive/2.6.tar.gz; cd Flye-2.6; make) and ran the same assembly command; this assembly finished within 20.5hrs.

Is the increase in runtime for flye2.7 something that comes naturally with the improvements you made, or is it maybe related to some issues? 

Here is the command I used
`flye --pacbio-corr 4463_A_CCS.fastq --meta --genome-size 100m --threads 40 --out-dir flye2.6_out_4463_ccs`

Here is the log file of the 2.7 assembly
https://www.dropbox.com/s/vz26mwjscoj0b8y/flye.log?dl=0

And here is the log file of the 2.6 assembly
https://www.dropbox.com/s/n15hrnofq5pw9ng/flye2.6.log?dl=0

I also want to mention that in both assemblies, I got a 4.1Mb circular contig which represents the closed genome of the most abundant organism (which is also the organism I am particularly interested in). This is super impressive and I am very happy with these results. Thanks again for this great software.

Cheers

bresyd

**Comment by mikolmogorov** [comment]
Hi,

First of all, it seems that 2.7 assembly is definitely better than 2.6: there is 100 Mb more of assembled sequence and the contiguity is higher. It probably should be more apparent with metrics that do not depend on total assembly size (like total length of contigs longer than X). I would also suggest CheckM analysis of contigs.

With respect to the slowdown - the first part is the increased time to build repeat graph, which is somewhat expected because more sequence was generated (two days still seems too much). But also, Flye surprisingly took two days to output the gfa graph. Looks like the current implementation is very inefficient - I am planning to fix it soon.

Mikhail

**Comment by bresyd** [comment]
Hi Mikhail,

thanks for your response and for trying to fix this issue. I might just wait until your fix is available before I start assembling further large datasets. Thanks also for pointing out what to look at when comparing different assemblies.

Cheers

**Comment by mikolmogorov** [comment]
@bresyd fix for the long GFA generation is in the `flye` branch now - feel free to try.

**Comment by bresyd** [comment]
Thanks a lot. 

I just want to make sure that I am now using your latest updated version. 

When I do `flye --version` should I get `2.7-b1587` or still `2.7-b1585`? 

I reinstalled flye today using two methods:
1. using conda as described in your installation instructions
2. `wget https://github.com/fenderglass/Flye/archive/2.7.tar.gz;
tar -xzf 2.7.tar.gz;
cd Flye-2.7;
make`

For both installations, I get `2.7-b1585` as version, hence I am not sure I installed the version that includes your latest changes.

Could you point me to the correct installation file/instructions in case I have so far missed it?

**Comment by bresyd** [comment]
I just tried a different way of installing and now I think I have the latest version, including the changes you recently made.

I installed the following way:
`git clone https://github.com/fenderglass/Flye; cd Flye; make`
Now when I do `bin/flye --version` I get `2.7-b1587`

I presume this version includes your latest changes?

**Comment by mikolmogorov** [comment]
@bresyd the last one is correct - I've put this change after 2.7 release.

**Comment by bresyd** [comment]
Hi Mikhail,

I repeated the same assembly using the updated flye version (2.7-b1587). The assembly took 99 hrs compared to the 121 hrs the 2.7 release took, so roughly 1 day faster. The assembly metrics are also slightly different now. 

I have put the log file here in case you want to have a look:
https://www.dropbox.com/s/9fzvcosfc0jg9h3/flye.log_flye2.7-b1587?dl=0

Cheers

**Comment by mikolmogorov** [comment]
@bresyd ok, thanks for letting me know! Looks like Gfa generation time is reasonable now (~15 minutes down from two days). 

Since the original issue is resolved, I'm closing the thread. Feel free to reopen if you have any follow ups! In the future versions, we are planning to further improve HiFi reads support.

Best,
Mikhail

**Comment by dcopetti** [comment]
Hi,
I have a similar issue with versions from the conda installation.
Due to some issues on the software version on a virtual machine I am using, I can't install Flye from GitHub repo, so if I do it via conda I get the version 2.7-b1585.
How do I get 2.7-b1587 via conda? is the faster gfa step only in 2.7-b1587 and not in 2.7-b1585?
Thanks

**Comment by mikolmogorov** [comment]
@dcopetti feel free to use 2.7.1 from bioconda - it already contains the fix.

**Comment by dcopetti** [comment]
Thanks Mikhail,
I am confused with version number now:
I did `conda update -c bioconda flye` , uninstalled and installed it back with `conda install -c bioconda flye`, that installed the package `bioconda/linux-64::flye-2.7-py37he513fc3_0`
and I still get
```
$ flye --version
2.7-b1585 
```
is this equivalent to the 2.7.1?
Thanks,
Dario

**Comment by mikolmogorov** [comment]
No, the version should be `2.7.1-b1590`. Make sure you have the latest bioconda package (2.7.1). If something is not working, try a fresh environment - it should install the latest version.

**Comment by dcopetti** [comment]
got it!, thanks for the details

Dario
